"""empty message

Revision ID: 324599ef953e
Revises: 
Create Date: 2020-12-07 13:25:54.542822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324599ef953e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
